name: listarHTML
on:
  push:
    branches:
      - main
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
     - name: Pegar-repositório
       uses: actions/checkout@v4

     - name: ListarHTML
       run: echo "lista completa de arquivos HTML"
            find . -type f -name "*.html" | wc -l
