name: usuarioPush

on:
  push:
    branches:
      - main
      
permissions:
  content: write

jobs:
  userPush:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    uses: actions/checkout@v4

    - name: comentar-usuario-push
      run: echo "Push feito por ${{ github.actor }}"
    
