name: listarArquivos
on:
  push:
    branches:
      - main
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
     - name: Pegar-repositório
       uses: actions/checkout@v4

     - name: ListaArquivos
       run: echo "lista completa"
            find . type f
