name: rodarDia

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 2'  

jobs:
  dia:
    runs-on: ubuntu-latest

    steps:
      - name: varDia
        run: varDia=$(TZ="America/Sao_Paulo" date '+%Y-%m-%d')


    
      - name: rodouDia
        run:  echo "Rodado no dia $varDia"
              
          
