name: rodarHora

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  

jobs:
  dia:
    runs-on: ubuntu-latest

    steps:
    
      - name: rodouHora
        run: |
          varHora=$(TZ="America/Sao_Paulo" date '+%H:%M')
          echo "Rodado na hora $varHora"
              
          
